from __future__ import annotations

import json
import unittest

from luminophore_shell.binding_registry import default_registry
from luminophore_shell.generated_bindings import binding_generation_id, serialize_binding_data, serialize_binding_lua


class GeneratedBindingsTests(unittest.TestCase):
    def test_data_payload_is_deterministic_and_contains_registered_actions_only(self) -> None:
        registry = default_registry()
        first = serialize_binding_data(registry)
        self.assertEqual(first, serialize_binding_data(default_registry()))
        payload = json.loads(first)
        self.assertEqual(payload["version"], 1)
        self.assertEqual(payload["generation_id"], binding_generation_id(registry))
        self.assertEqual(len(payload["generation_id"]), 64)
        self.assertEqual(
            [row["action_id"] for row in payload["bindings"]],
            [action.action_id for action in registry.actions],
        )
        self.assertFalse(any("command" in row or "argv" in row for row in payload["bindings"]))

    def test_lua_payload_is_deterministic_data_without_executable_commands(self) -> None:
        payload = serialize_binding_lua(default_registry())
        self.assertEqual(payload, serialize_binding_lua(default_registry()))
        text = payload.decode("utf-8")
        self.assertTrue(text.startswith("-- Generated by Luminophore binding registry"))
        self.assertIn('action_id = "shell.settings"', text)
        self.assertIn('action_id = "view.wide.toggle"', text)
        self.assertIn(f'generation_id = "{binding_generation_id(default_registry())}"', text)
        self.assertIn("recovery = true", text)
        self.assertNotIn("exec_cmd", text)
        self.assertNotIn("hyprctl", text)
        self.assertNotIn("os.execute", text)


if __name__ == "__main__":
    unittest.main()
