"""Generate native declaration metadata from the Shell's owned data models.

This is source generation, not a compositor build. --check never writes.
"""
from dataclasses import fields, is_dataclass
import json
from pathlib import Path
import sys
from typing import get_type_hints

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from luminophore_shell.config import ShellConfig, COLLECTION_ENCODINGS
from luminophore_shell.binding_registry import default_registry


def declarations(model, prefix=''):
    for key, kind in get_type_hints(model).items():
        path = prefix + key
        if path in ('path', 'devices'):
            continue
        if path in COLLECTION_ENCODINGS:
            yield path, COLLECTION_ENCODINGS[path]
        elif is_dataclass(kind):
            yield from declarations(kind, path + '.')
        elif kind in (str, bool, int, float):
            yield path, kind.__name__
        else:
            raise ValueError('unrepresented desktop field: ' + path)


def render():
    quote = lambda value: json.dumps(value, ensure_ascii=True)
    text = '// Generated by config/schema/generate_desktop_settings.py; do not edit.\n#pragma once\n#include <map>\n#include <string>\n#include <vector>\nnamespace Luminophore::Settings {\n'
    text += 'inline const std::map<std::string, std::string> SHELL_FIELD_TYPES = {\n'
    for name, kind in sorted(declarations(ShellConfig)):
        text += '    {' + quote(name) + ', ' + quote(kind) + '},\n'
    text += '};\nstruct SBindingDeclaration { std::string action, chord, group; bool locked = false, repeating = false, release = false, nonConsuming = false, recovery = false; };\n'
    text += 'inline const std::vector<SBindingDeclaration> BINDING_DECLARATIONS = {\n'
    for action in default_registry().actions:
        values = [quote(action.action_id), quote(action.chord or ''), quote(action.group_id)]
        values += [str(getattr(action.flags, field)).lower() for field in ('locked', 'repeating', 'release', 'non_consuming')]
        values += [str(action.recovery).lower()]
        text += '    {' + ', '.join(values) + '},\n'
    return text + '};\n}\n'


if __name__ == '__main__':
    target = ROOT.parent / 'compositor/src/config/luminophore/GeneratedDesktopSettings.hpp'
    result = render()
    if '--check' in sys.argv:
        if not target.exists() or target.read_text() != result:
            raise SystemExit('desktop declarations are stale')
    else:
        target.write_text(result)
