"""Generate shared scalar contracts; input is product schema, never user data."""
import argparse
import json
from pathlib import Path
import pprint
import subprocess


def generate(root: Path, check: bool = False) -> bool:
    schema = json.loads((root / 'config/schema/settings.json').read_text())
    fields = schema['fields']
    keys = [f['key'] for f in fields]
    if len(keys) != len(set(keys)):
        raise ValueError('duplicate schema key')
    types = {'int': 'int64_t', 'float': 'double', 'bool': 'bool', 'str': 'std::string'}
    def literal(value, kind):
        if kind == 'str':
            return 'std::string{' + json.dumps(value) + '}'
        if kind == 'int':
            return 'int64_t{' + str(value) + '}'
        return json.dumps(value)
    header = '''// Generated by config/schema/generate_settings.py; do not edit.
#pragma once
#include <cstdint>
#include <map>
#include <string>
#include <variant>

namespace Luminophore::Settings {
    using Value = std::variant<int64_t, double, bool, std::string>;
    using Snapshot = std::map<std::string, Value>;
    Snapshot defaults();
    // Empty string means valid. Validation does not mutate the input.
    std::string validate(const Snapshot& values);
}
'''
    cpp = ['// Generated by config/schema/generate_settings.py; do not edit.',
           '#include "GeneratedSettings.hpp"', '#include <cmath>', '#include <regex>',
           'namespace Luminophore::Settings {', 'Snapshot defaults() {', '    return {']
    for field in fields:
        cpp.append('        {' + json.dumps(field['key']) + ', ' + literal(field['default'], field['type']) + '},')
    cpp += ['    };', '}', 'std::string validate(const Snapshot& values) {',
            '    for (const auto& [key, value] : values) {']
    for i, field in enumerate(fields):
        key, kind = field['key'], field['type']
        cpp.append('        ' + ('if' if i == 0 else 'else if') + ' (key == ' + json.dumps(key) + ') {')
        cpp.append('            const auto* v = std::get_if<' + types[kind] + '>(&value);')
        cpp.append('            if (!v) return key + ": type";')
        if kind == 'float':
            cpp.append('            if (!std::isfinite(*v)) return key + ": finite";')
        if field['minimum'] is not None:
            cpp.append('            if (*v < ' + str(field['minimum']) + ') return key + ": minimum";')
        if field['maximum'] is not None:
            cpp.append('            if (*v > ' + str(field['maximum']) + ') return key + ": maximum";')
        if field.get('pattern'):
            cpp.append('            static const std::regex pattern(' + json.dumps(field['pattern']) + ');')
            cpp.append('            if (!std::regex_match(*v, pattern)) return key + ": format";')
        if field['choices']:
            cpp.append('            if (' + ' && '.join('*v != ' + literal(c, kind) for c in field['choices']) + ') return key + ": choice";')
        cpp.append('        }')
    cpp += ['        else return key + ": unknown";', '    }',
            '    auto resolved = defaults();', '    for (const auto& [key, value] : values) resolved[key] = value;']
    for c in schema['constraints']:
        if c['kind'] == 'less_equal':
            cpp.append('    if (std::get<double>(resolved.at(' + json.dumps(c['left']) + ')) > std::get<double>(resolved.at(' + json.dumps(c['right']) + '))) return ' + json.dumps(c['left'] + ': ordering') + ';')
        elif c['kind'] == 'requires':
            kind = next(f['type'] for f in fields if f['key'] == c['key'])
            cpp.append('    if (std::get<' + types[kind] + '>(resolved.at(' + json.dumps(c['key']) + ')) == ' + literal(c['value'], kind) + ' && !std::get<bool>(resolved.at(' + json.dumps(c['requires']) + '))) return ' + json.dumps(c['key'] + ': requires') + ';')
        else:
            raise ValueError('unknown constraint')
    cpp += ['    return {};', '}', '}']
    outputs = {
        root / 'config/luminophore_shell/generated_settings.py': '# Generated by schema/generate_settings.py; do not edit.\nSCHEMA = ' + pprint.pformat(schema, sort_dicts=False) + '\n',
        root / 'compositor/src/config/luminophore/GeneratedSettings.hpp': header,
        root / 'compositor/src/config/luminophore/GeneratedSettings.cpp': '\n'.join(cpp) + '\n',
    }
    stale = False
    for path, text in outputs.items():
        if path.suffix in ('.hpp', '.cpp'):
            text = subprocess.run(['clang-format', '--assume-filename=' + str(path)], input=text,
                                  text=True, capture_output=True, check=True).stdout
        if check:
            if not path.exists() or path.read_text() != text:
                print('stale generated settings:', path)
                stale = True
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text)
    return not stale


if __name__ == '__main__':
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--check', action='store_true')
    p.add_argument('--root', type=Path, default=Path(__file__).resolve().parents[2])
    a = p.parse_args()
    raise SystemExit(0 if generate(a.root, a.check) else 1)
