// Generated by config/schema/generate_settings.py; do not edit.
#include "GeneratedSettings.hpp"
#include <cmath>
#include <regex>
namespace Luminophore::Settings {
    Snapshot defaults() {
        return {
            {"compositor.default_view_columns", int64_t{1}},
            {"compositor.default_view_rows", int64_t{1}},
            {"compositor.gaps_in", int64_t{0}},
            {"compositor.gaps_out", int64_t{0}},
            {"compositor.border_size", int64_t{5}},
            {"compositor.rounding", int64_t{7}},
            {"compositor.active_opacity", 1.0},
            {"compositor.inactive_opacity", 1.0},
            {"compositor.dim_special", 0.3},
            {"compositor.blur_enabled", true},
            {"compositor.blur_size", int64_t{5}},
            {"compositor.blur_passes", int64_t{1}},
            {"compositor.vrr", int64_t{3}},
            {"motion.enabled", true},
            {"motion.preset", std::string{"balanced"}},
            {"motion.speed", 1.0},
            {"visual.schema_version", int64_t{1}},
            {"visual.enabled", true},
            {"visual.breathing", true},
            {"visual.preset", std::string{"balanced"}},
            {"visual.intensity", 0.42},
            {"input.repeat_rate", int64_t{25}},
            {"input.repeat_delay", int64_t{600}},
            {"input.sensitivity", 0.0},
            {"input.scroll_factor", 1.0},
            {"input.natural_scroll", false},
            {"input.left_handed", false},
            {"input.force_no_accel", false},
            {"input.kb_layout", std::string{"us"}},
            {"input.kb_model", std::string{"pc105"}},
            {"input.kb_variant", std::string{""}},
            {"input.kb_options", std::string{""}},
            {"input.kb_rules", std::string{"evdev"}},
            {"touchpad.disable_while_typing", true},
            {"touchpad.natural_scroll", false},
            {"touchpad.scroll_factor", 1.0},
            {"touchpad.middle_button_emulation", false},
            {"touchpad.tap_button_map", std::string{""}},
            {"touchpad.clickfinger_behavior", false},
            {"touchpad.tap_to_click", true},
            {"touchpad.drag_lock", int64_t{0}},
            {"touchpad.tap_and_drag", true},
            {"touchpad.flip_x", false},
            {"touchpad.flip_y", false},
            {"touchpad.drag_3fg", int64_t{0}},
            {"touchdevice.transform", int64_t{0}},
            {"touchdevice.output", std::string{"[[Auto]]"}},
            {"touchdevice.enabled", true},
            {"virtualkeyboard.share_states", int64_t{2}},
            {"virtualkeyboard.release_pressed_on_close", false},
            {"tablet.transform", int64_t{0}},
            {"tablet.output", std::string{""}},
            {"tablet.absolute_region_position", false},
            {"tablet.relative_input", false},
            {"tablet.left_handed", false},
            {"tablet.region_position_x", 0.0},
            {"tablet.region_position_y", 0.0},
            {"tablet.region_size_x", 0.0},
            {"tablet.region_size_y", 0.0},
            {"tablet.active_area_size_x", 0.0},
            {"tablet.active_area_size_y", 0.0},
            {"tablet.active_area_position_x", 0.0},
            {"tablet.active_area_position_y", 0.0},
            {"tablettool.eraser_button_mode", int64_t{0}},
            {"tablettool.eraser_button_override", int64_t{0}},
            {"tablettool.pressure_range_min", -1.0},
            {"tablettool.pressure_range_max", -1.0},
            {"input.scroll_method", std::string{""}},
            {"input.scroll_button", int64_t{0}},
            {"input.scroll_button_lock", false},
            {"input.rotation", int64_t{0}},
            {"input.numlock_by_default", false},
            {"input.resolve_binds_by_sym", false},
            {"input.follow_mouse", int64_t{1}},
            {"input.follow_mouse_threshold", 0.0},
            {"input.mouse_refocus", true},
            {"input.follow_mouse_shrink", int64_t{0}},
            {"input.off_window_axis_events", int64_t{1}},
            {"input.emulate_discrete_scroll", int64_t{1}},
            {"input.focus_on_close", int64_t{0}},
            {"input.float_switch_override_focus", int64_t{1}},
            {"input.accel_profile", std::string{""}},
            {"input.scroll_points", std::string{""}},
            {"input.kb_file", std::string{""}},
            {"input.kb_snapshot", std::string{""}},
            {"input.drag_threshold", int64_t{0}},
            {"input.scroll_event_delay", int64_t{300}},
            {"input.cursor_inactive_timeout", 0.0},
            {"input.cursor_no_warps", false},
            {"input.cursor_persistent_warps", false},
            {"input.cursor_hide_on_key_press", false},
            {"input.cursor_hide_on_touch", true},
            {"input.cursor_hide_on_tablet", false},
            {"input.cursor_warp_back_after_non_mouse_input", false},
            {"input.resize_on_border", false},
            {"input.extend_border_grab_area", int64_t{15}},
            {"input.resize_on_border_inner_area", int64_t{0}},
            {"input.hover_icon_on_border", true},
            {"input.resize_corner", int64_t{0}},
            {"input.close_gesture_timeout", int64_t{1000}},
            {"compositor.fullscreen_opacity", 1.0},
            {"compositor.dim_inactive", false},
            {"compositor.dim_modal", true},
            {"compositor.dim_strength", 0.5},
            {"compositor.dim_around", 0.4},
            {"compositor.blur_popups", false},
            {"compositor.blur_input_methods", false},
            {"compositor.render_unfocused_fps", int64_t{15}},
            {"compositor.zoom_rigid", false},
            {"compositor.zoom_detached_camera", true},
            {"compositor.zoom_disable_aa", false},
            {"compositor.pointer_focus_output", true},
            {"compositor.fullscreen_focus_policy", int64_t{2}},
            {"compositor.fullscreen_after_close", false},
            {"compositor.xwayland_nearest_neighbor", true},
            {"compositor.allow_tearing", false},
            {"compositor.cursor_start_output", std::string{""}},
            {"compositor.zoom_factor", 1.0},
            {"compositor.locale", std::string{""}},
            {"compositor.font_family", std::string{"Sans"}},
            {"compositor.wake_on_key", false},
            {"compositor.wake_on_pointer", false},
            {"compositor.display_idle_minutes", int64_t{0}},
            {"compositor.primary_selection", true},
            {"compositor.auto_hdr", int64_t{1}},
            {"compositor.sdr_transfer", std::string{"default"}},
            {"compositor.icc_vcgt", true},
            {"compositor.xwayland_native_pixels", false},
            {"compositor.background_color", std::string{"ff111111"}},
            {"compositor.shadow_enabled", true},
            {"compositor.shadow_range", int64_t{4}},
            {"compositor.shadow_power", int64_t{3}},
            {"compositor.shadow_sharp", false},
            {"compositor.shadow_color", std::string{"ee1a1a1a 0deg"}},
            {"compositor.shadow_inactive_color", std::string{"inherit"}},
            {"compositor.shadow_scale", 1.0},
            {"compositor.shadow_offset_x", 0.0},
            {"compositor.shadow_offset_y", 0.0},
            {"compositor.float_gap_top", int64_t{0}},
            {"compositor.float_gap_right", int64_t{0}},
            {"compositor.float_gap_bottom", int64_t{0}},
            {"compositor.float_gap_left", int64_t{0}},
            {"compositor.color_management", true},
            {"compositor.lock_background", false},
            {"compositor.lock_blur", false},
            {"compositor.swallow_enabled", true},
            {"compositor.swallow_regex", std::string{"(kitty|ghostty|[Kk]onsole|Alacritty|gnome-terminal|xfce[0-9]?-terminal)"}},
            {"compositor.swallow_exception_regex", std::string{""}},
            {"compositor.screen_shader", std::string{""}},
            {"compositor.motion_blur_enabled", false},
            {"compositor.motion_blur_samples", int64_t{7}},
            {"compositor.snap_enabled", false},
            {"compositor.snap_window_gap", int64_t{10}},
            {"compositor.snap_monitor_gap", int64_t{10}},
            {"compositor.snap_border_overlap", false},
            {"compositor.snap_respect_gaps", false},
        };
    }
    std::string validate(const Snapshot& values) {
        for (const auto& [key, value] : values) {
            if (key == "compositor.default_view_columns") {
                const auto* v = std::get_if<int64_t>(&value);
                if (!v)
                    return key + ": type";
                if (*v < 1)
                    return key + ": minimum";
                if (*v > 64)
                    return key + ": maximum";
            } else if (key == "compositor.default_view_rows") {
                const auto* v = std::get_if<int64_t>(&value);
                if (!v)
                    return key + ": type";
                if (*v < 1)
                    return key + ": minimum";
                if (*v > 64)
                    return key + ": maximum";
            } else if (key == "compositor.gaps_in") {
                const auto* v = std::get_if<int64_t>(&value);
                if (!v)
                    return key + ": type";
                if (*v < 0)
                    return key + ": minimum";
                if (*v > 100)
                    return key + ": maximum";
            } else if (key == "compositor.gaps_out") {
                const auto* v = std::get_if<int64_t>(&value);
                if (!v)
                    return key + ": type";
                if (*v < 0)
                    return key + ": minimum";
                if (*v > 100)
                    return key + ": maximum";
            } else if (key == "compositor.border_size") {
                const auto* v = std::get_if<int64_t>(&value);
                if (!v)
                    return key + ": type";
                if (*v < 0)
                    return key + ": minimum";
                if (*v > 20)
                    return key + ": maximum";
            } else if (key == "compositor.rounding") {
                const auto* v = std::get_if<int64_t>(&value);
                if (!v)
                    return key + ": type";
                if (*v < 0)
                    return key + ": minimum";
                if (*v > 100)
                    return key + ": maximum";
            } else if (key == "compositor.active_opacity") {
                const auto* v = std::get_if<double>(&value);
                if (!v)
                    return key + ": type";
                if (!std::isfinite(*v))
                    return key + ": finite";
                if (*v < 0.1)
                    return key + ": minimum";
                if (*v > 1.0)
                    return key + ": maximum";
            } else if (key == "compositor.inactive_opacity") {
                const auto* v = std::get_if<double>(&value);
                if (!v)
                    return key + ": type";
                if (!std::isfinite(*v))
                    return key + ": finite";
                if (*v < 0.1)
                    return key + ": minimum";
                if (*v > 1.0)
                    return key + ": maximum";
            } else if (key == "compositor.dim_special") {
                const auto* v = std::get_if<double>(&value);
                if (!v)
                    return key + ": type";
                if (!std::isfinite(*v))
                    return key + ": finite";
                if (*v < 0.0)
                    return key + ": minimum";
                if (*v > 1.0)
                    return key + ": maximum";
            } else if (key == "compositor.blur_enabled") {
                const auto* v = std::get_if<bool>(&value);
                if (!v)
                    return key + ": type";
            } else if (key == "compositor.blur_size") {
                const auto* v = std::get_if<int64_t>(&value);
                if (!v)
                    return key + ": type";
                if (*v < 1)
                    return key + ": minimum";
                if (*v > 20)
                    return key + ": maximum";
            } else if (key == "compositor.blur_passes") {
                const auto* v = std::get_if<int64_t>(&value);
                if (!v)
                    return key + ": type";
                if (*v < 1)
                    return key + ": minimum";
                if (*v > 10)
                    return key + ": maximum";
            } else if (key == "compositor.vrr") {
                const auto* v = std::get_if<int64_t>(&value);
                if (!v)
                    return key + ": type";
                if (*v != int64_t{0} && *v != int64_t{1} && *v != int64_t{2} && *v != int64_t{3})
                    return key + ": choice";
            } else if (key == "motion.enabled") {
                const auto* v = std::get_if<bool>(&value);
                if (!v)
                    return key + ": type";
            } else if (key == "motion.preset") {
                const auto* v = std::get_if<std::string>(&value);
                if (!v)
                    return key + ": type";
                if (*v != std::string{"fast"} && *v != std::string{"balanced"} && *v != std::string{"smooth"} && *v != std::string{"custom"})
                    return key + ": choice";
            } else if (key == "motion.speed") {
                const auto* v = std::get_if<double>(&value);
                if (!v)
                    return key + ": type";
                if (!std::isfinite(*v))
                    return key + ": finite";
                if (*v < 0.1)
                    return key + ": minimum";
                if (*v > 10.0)
                    return key + ": maximum";
            } else if (key == "visual.schema_version") {
                const auto* v = std::get_if<int64_t>(&value);
                if (!v)
                    return key + ": type";
                if (*v < 1)
                    return key + ": minimum";
                if (*v > 1)
                    return key + ": maximum";
            } else if (key == "visual.enabled") {
                const auto* v = std::get_if<bool>(&value);
                if (!v)
                    return key + ": type";
            } else if (key == "visual.breathing") {
                const auto* v = std::get_if<bool>(&value);
                if (!v)
                    return key + ": type";
            } else if (key == "visual.preset") {
                const auto* v = std::get_if<std::string>(&value);
                if (!v)
                    return key + ": type";
                if (*v != std::string{"balanced"})
                    return key + ": choice";
            } else if (key == "visual.intensity") {
                const auto* v = std::get_if<double>(&value);
                if (!v)
                    return key + ": type";
                if (!std::isfinite(*v))
                    return key + ": finite";
                if (*v < 0.0)
                    return key + ": minimum";
                if (*v > 3.0)
                    return key + ": maximum";
            } else if (key == "input.repeat_rate") {
                const auto* v = std::get_if<int64_t>(&value);
                if (!v)
                    return key + ": type";
                if (*v < 0)
                    return key + ": minimum";
                if (*v > 200)
                    return key + ": maximum";
            } else if (key == "input.repeat_delay") {
                const auto* v = std::get_if<int64_t>(&value);
                if (!v)
                    return key + ": type";
                if (*v < 0)
                    return key + ": minimum";
                if (*v > 2000)
                    return key + ": maximum";
            } else if (key == "input.sensitivity") {
                const auto* v = std::get_if<double>(&value);
                if (!v)
                    return key + ": type";
                if (!std::isfinite(*v))
                    return key + ": finite";
                if (*v < -1.0)
                    return key + ": minimum";
                if (*v > 1.0)
                    return key + ": maximum";
            } else if (key == "input.scroll_factor") {
                const auto* v = std::get_if<double>(&value);
                if (!v)
                    return key + ": type";
                if (!std::isfinite(*v))
                    return key + ": finite";
                if (*v < 0.0)
                    return key + ": minimum";
                if (*v > 2.0)
                    return key + ": maximum";
            } else if (key == "input.natural_scroll") {
                const auto* v = std::get_if<bool>(&value);
                if (!v)
                    return key + ": type";
            } else if (key == "input.left_handed") {
                const auto* v = std::get_if<bool>(&value);
                if (!v)
                    return key + ": type";
            } else if (key == "input.force_no_accel") {
                const auto* v = std::get_if<bool>(&value);
                if (!v)
                    return key + ": type";
            } else if (key == "input.kb_layout") {
                const auto* v = std::get_if<std::string>(&value);
                if (!v)
                    return key + ": type";
            } else if (key == "input.kb_model") {
                const auto* v = std::get_if<std::string>(&value);
                if (!v)
                    return key + ": type";
            } else if (key == "input.kb_variant") {
                const auto* v = std::get_if<std::string>(&value);
                if (!v)
                    return key + ": type";
            } else if (key == "input.kb_options") {
                const auto* v = std::get_if<std::string>(&value);
                if (!v)
                    return key + ": type";
            } else if (key == "input.kb_rules") {
                const auto* v = std::get_if<std::string>(&value);
                if (!v)
                    return key + ": type";
            } else if (key == "touchpad.disable_while_typing") {
                const auto* v = std::get_if<bool>(&value);
                if (!v)
                    return key + ": type";
            } else if (key == "touchpad.natural_scroll") {
                const auto* v = std::get_if<bool>(&value);
                if (!v)
                    return key + ": type";
            } else if (key == "touchpad.scroll_factor") {
                const auto* v = std::get_if<double>(&value);
                if (!v)
                    return key + ": type";
                if (!std::isfinite(*v))
                    return key + ": finite";
                if (*v < 0)
                    return key + ": minimum";
                if (*v > 2)
                    return key + ": maximum";
            } else if (key == "touchpad.middle_button_emulation") {
                const auto* v = std::get_if<bool>(&value);
                if (!v)
                    return key + ": type";
            } else if (key == "touchpad.tap_button_map") {
                const auto* v = std::get_if<std::string>(&value);
                if (!v)
                    return key + ": type";
                if (*v != std::string{""} && *v != std::string{"lrm"} && *v != std::string{"lmr"})
                    return key + ": choice";
            } else if (key == "touchpad.clickfinger_behavior") {
                const auto* v = std::get_if<bool>(&value);
                if (!v)
                    return key + ": type";
            } else if (key == "touchpad.tap_to_click") {
                const auto* v = std::get_if<bool>(&value);
                if (!v)
                    return key + ": type";
            } else if (key == "touchpad.drag_lock") {
                const auto* v = std::get_if<int64_t>(&value);
                if (!v)
                    return key + ": type";
                if (*v < 0)
                    return key + ": minimum";
                if (*v > 2)
                    return key + ": maximum";
            } else if (key == "touchpad.tap_and_drag") {
                const auto* v = std::get_if<bool>(&value);
                if (!v)
                    return key + ": type";
            } else if (key == "touchpad.flip_x") {
                const auto* v = std::get_if<bool>(&value);
                if (!v)
                    return key + ": type";
            } else if (key == "touchpad.flip_y") {
                const auto* v = std::get_if<bool>(&value);
                if (!v)
                    return key + ": type";
            } else if (key == "touchpad.drag_3fg") {
                const auto* v = std::get_if<int64_t>(&value);
                if (!v)
                    return key + ": type";
                if (*v < 0)
                    return key + ": minimum";
                if (*v > 2)
                    return key + ": maximum";
            } else if (key == "touchdevice.transform") {
                const auto* v = std::get_if<int64_t>(&value);
                if (!v)
                    return key + ": type";
                if (*v < 0)
                    return key + ": minimum";
                if (*v > 6)
                    return key + ": maximum";
            } else if (key == "touchdevice.output") {
                const auto* v = std::get_if<std::string>(&value);
                if (!v)
                    return key + ": type";
            } else if (key == "touchdevice.enabled") {
                const auto* v = std::get_if<bool>(&value);
                if (!v)
                    return key + ": type";
            } else if (key == "virtualkeyboard.share_states") {
                const auto* v = std::get_if<int64_t>(&value);
                if (!v)
                    return key + ": type";
                if (*v < 0)
                    return key + ": minimum";
                if (*v > 2)
                    return key + ": maximum";
            } else if (key == "virtualkeyboard.release_pressed_on_close") {
                const auto* v = std::get_if<bool>(&value);
                if (!v)
                    return key + ": type";
            } else if (key == "tablet.transform") {
                const auto* v = std::get_if<int64_t>(&value);
                if (!v)
                    return key + ": type";
                if (*v < 0)
                    return key + ": minimum";
                if (*v > 6)
                    return key + ": maximum";
            } else if (key == "tablet.output") {
                const auto* v = std::get_if<std::string>(&value);
                if (!v)
                    return key + ": type";
            } else if (key == "tablet.absolute_region_position") {
                const auto* v = std::get_if<bool>(&value);
                if (!v)
                    return key + ": type";
            } else if (key == "tablet.relative_input") {
                const auto* v = std::get_if<bool>(&value);
                if (!v)
                    return key + ": type";
            } else if (key == "tablet.left_handed") {
                const auto* v = std::get_if<bool>(&value);
                if (!v)
                    return key + ": type";
            } else if (key == "tablet.region_position_x") {
                const auto* v = std::get_if<double>(&value);
                if (!v)
                    return key + ": type";
                if (!std::isfinite(*v))
                    return key + ": finite";
                if (*v < -20000)
                    return key + ": minimum";
                if (*v > 20000)
                    return key + ": maximum";
            } else if (key == "tablet.region_position_y") {
                const auto* v = std::get_if<double>(&value);
                if (!v)
                    return key + ": type";
                if (!std::isfinite(*v))
                    return key + ": finite";
                if (*v < -20000)
                    return key + ": minimum";
                if (*v > 20000)
                    return key + ": maximum";
            } else if (key == "tablet.region_size_x") {
                const auto* v = std::get_if<double>(&value);
                if (!v)
                    return key + ": type";
                if (!std::isfinite(*v))
                    return key + ": finite";
                if (*v < -100)
                    return key + ": minimum";
                if (*v > 4000)
                    return key + ": maximum";
            } else if (key == "tablet.region_size_y") {
                const auto* v = std::get_if<double>(&value);
                if (!v)
                    return key + ": type";
                if (!std::isfinite(*v))
                    return key + ": finite";
                if (*v < -100)
                    return key + ": minimum";
                if (*v > 4000)
                    return key + ": maximum";
            } else if (key == "tablet.active_area_size_x") {
                const auto* v = std::get_if<double>(&value);
                if (!v)
                    return key + ": type";
                if (!std::isfinite(*v))
                    return key + ": finite";
                if (*v < 0)
                    return key + ": minimum";
                if (*v > 500)
                    return key + ": maximum";
            } else if (key == "tablet.active_area_size_y") {
                const auto* v = std::get_if<double>(&value);
                if (!v)
                    return key + ": type";
                if (!std::isfinite(*v))
                    return key + ": finite";
                if (*v < 0)
                    return key + ": minimum";
                if (*v > 500)
                    return key + ": maximum";
            } else if (key == "tablet.active_area_position_x") {
                const auto* v = std::get_if<double>(&value);
                if (!v)
                    return key + ": type";
                if (!std::isfinite(*v))
                    return key + ": finite";
                if (*v < 0)
                    return key + ": minimum";
                if (*v > 500)
                    return key + ": maximum";
            } else if (key == "tablet.active_area_position_y") {
                const auto* v = std::get_if<double>(&value);
                if (!v)
                    return key + ": type";
                if (!std::isfinite(*v))
                    return key + ": finite";
                if (*v < 0)
                    return key + ": minimum";
                if (*v > 500)
                    return key + ": maximum";
            } else if (key == "tablettool.eraser_button_mode") {
                const auto* v = std::get_if<int64_t>(&value);
                if (!v)
                    return key + ": type";
                if (*v < 0)
                    return key + ": minimum";
                if (*v > 6)
                    return key + ": maximum";
            } else if (key == "tablettool.eraser_button_override") {
                const auto* v = std::get_if<int64_t>(&value);
                if (!v)
                    return key + ": type";
                if (*v < 0)
                    return key + ": minimum";
                if (*v > 2147483647)
                    return key + ": maximum";
            } else if (key == "tablettool.pressure_range_min") {
                const auto* v = std::get_if<double>(&value);
                if (!v)
                    return key + ": type";
                if (!std::isfinite(*v))
                    return key + ": finite";
                if (*v < -1)
                    return key + ": minimum";
                if (*v > 1)
                    return key + ": maximum";
            } else if (key == "tablettool.pressure_range_max") {
                const auto* v = std::get_if<double>(&value);
                if (!v)
                    return key + ": type";
                if (!std::isfinite(*v))
                    return key + ": finite";
                if (*v < -1)
                    return key + ": minimum";
                if (*v > 1)
                    return key + ": maximum";
            } else if (key == "input.scroll_method") {
                const auto* v = std::get_if<std::string>(&value);
                if (!v)
                    return key + ": type";
                if (*v != std::string{""} && *v != std::string{"2fg"} && *v != std::string{"edge"} && *v != std::string{"on_button_down"} && *v != std::string{"no_scroll"})
                    return key + ": choice";
            } else if (key == "input.scroll_button") {
                const auto* v = std::get_if<int64_t>(&value);
                if (!v)
                    return key + ": type";
                if (*v < 0)
                    return key + ": minimum";
                if (*v > 300)
                    return key + ": maximum";
            } else if (key == "input.scroll_button_lock") {
                const auto* v = std::get_if<bool>(&value);
                if (!v)
                    return key + ": type";
            } else if (key == "input.rotation") {
                const auto* v = std::get_if<int64_t>(&value);
                if (!v)
                    return key + ": type";
                if (*v < 0)
                    return key + ": minimum";
                if (*v > 359)
                    return key + ": maximum";
            } else if (key == "input.numlock_by_default") {
                const auto* v = std::get_if<bool>(&value);
                if (!v)
                    return key + ": type";
            } else if (key == "input.resolve_binds_by_sym") {
                const auto* v = std::get_if<bool>(&value);
                if (!v)
                    return key + ": type";
            } else if (key == "input.follow_mouse") {
                const auto* v = std::get_if<int64_t>(&value);
                if (!v)
                    return key + ": type";
                if (*v < 0)
                    return key + ": minimum";
                if (*v > 3)
                    return key + ": maximum";
            } else if (key == "input.follow_mouse_threshold") {
                const auto* v = std::get_if<double>(&value);
                if (!v)
                    return key + ": type";
                if (!std::isfinite(*v))
                    return key + ": finite";
            } else if (key == "input.mouse_refocus") {
                const auto* v = std::get_if<bool>(&value);
                if (!v)
                    return key + ": type";
            } else if (key == "input.follow_mouse_shrink") {
                const auto* v = std::get_if<int64_t>(&value);
                if (!v)
                    return key + ": type";
                if (*v < 0)
                    return key + ": minimum";
                if (*v > 300)
                    return key + ": maximum";
            } else if (key == "input.off_window_axis_events") {
                const auto* v = std::get_if<int64_t>(&value);
                if (!v)
                    return key + ": type";
                if (*v < 0)
                    return key + ": minimum";
                if (*v > 3)
                    return key + ": maximum";
            } else if (key == "input.emulate_discrete_scroll") {
                const auto* v = std::get_if<int64_t>(&value);
                if (!v)
                    return key + ": type";
                if (*v < 0)
                    return key + ": minimum";
                if (*v > 2)
                    return key + ": maximum";
            } else if (key == "input.focus_on_close") {
                const auto* v = std::get_if<int64_t>(&value);
                if (!v)
                    return key + ": type";
                if (*v < 0)
                    return key + ": minimum";
                if (*v > 2)
                    return key + ": maximum";
            } else if (key == "input.float_switch_override_focus") {
                const auto* v = std::get_if<int64_t>(&value);
                if (!v)
                    return key + ": type";
                if (*v < 0)
                    return key + ": minimum";
                if (*v > 2)
                    return key + ": maximum";
            } else if (key == "input.accel_profile") {
                const auto* v = std::get_if<std::string>(&value);
                if (!v)
                    return key + ": type";
            } else if (key == "input.scroll_points") {
                const auto* v = std::get_if<std::string>(&value);
                if (!v)
                    return key + ": type";
            } else if (key == "input.kb_file") {
                const auto* v = std::get_if<std::string>(&value);
                if (!v)
                    return key + ": type";
            } else if (key == "input.kb_snapshot") {
                const auto* v = std::get_if<std::string>(&value);
                if (!v)
                    return key + ": type";
            } else if (key == "input.drag_threshold") {
                const auto* v = std::get_if<int64_t>(&value);
                if (!v)
                    return key + ": type";
                if (*v < 0)
                    return key + ": minimum";
                if (*v > 2147483647)
                    return key + ": maximum";
            } else if (key == "input.scroll_event_delay") {
                const auto* v = std::get_if<int64_t>(&value);
                if (!v)
                    return key + ": type";
                if (*v < 0)
                    return key + ": minimum";
                if (*v > 2000)
                    return key + ": maximum";
            } else if (key == "input.cursor_inactive_timeout") {
                const auto* v = std::get_if<double>(&value);
                if (!v)
                    return key + ": type";
                if (!std::isfinite(*v))
                    return key + ": finite";
                if (*v < 0)
                    return key + ": minimum";
                if (*v > 20)
                    return key + ": maximum";
            } else if (key == "input.cursor_no_warps") {
                const auto* v = std::get_if<bool>(&value);
                if (!v)
                    return key + ": type";
            } else if (key == "input.cursor_persistent_warps") {
                const auto* v = std::get_if<bool>(&value);
                if (!v)
                    return key + ": type";
            } else if (key == "input.cursor_hide_on_key_press") {
                const auto* v = std::get_if<bool>(&value);
                if (!v)
                    return key + ": type";
            } else if (key == "input.cursor_hide_on_touch") {
                const auto* v = std::get_if<bool>(&value);
                if (!v)
                    return key + ": type";
            } else if (key == "input.cursor_hide_on_tablet") {
                const auto* v = std::get_if<bool>(&value);
                if (!v)
                    return key + ": type";
            } else if (key == "input.cursor_warp_back_after_non_mouse_input") {
                const auto* v = std::get_if<bool>(&value);
                if (!v)
                    return key + ": type";
            } else if (key == "input.resize_on_border") {
                const auto* v = std::get_if<bool>(&value);
                if (!v)
                    return key + ": type";
            } else if (key == "input.extend_border_grab_area") {
                const auto* v = std::get_if<int64_t>(&value);
                if (!v)
                    return key + ": type";
                if (*v < 0)
                    return key + ": minimum";
                if (*v > 100)
                    return key + ": maximum";
            } else if (key == "input.resize_on_border_inner_area") {
                const auto* v = std::get_if<int64_t>(&value);
                if (!v)
                    return key + ": type";
                if (*v < 0)
                    return key + ": minimum";
                if (*v > 100)
                    return key + ": maximum";
            } else if (key == "input.hover_icon_on_border") {
                const auto* v = std::get_if<bool>(&value);
                if (!v)
                    return key + ": type";
            } else if (key == "input.resize_corner") {
                const auto* v = std::get_if<int64_t>(&value);
                if (!v)
                    return key + ": type";
                if (*v < 0)
                    return key + ": minimum";
                if (*v > 4)
                    return key + ": maximum";
            } else if (key == "input.close_gesture_timeout") {
                const auto* v = std::get_if<int64_t>(&value);
                if (!v)
                    return key + ": type";
                if (*v < 10)
                    return key + ": minimum";
                if (*v > 2000)
                    return key + ": maximum";
            } else if (key == "compositor.fullscreen_opacity") {
                const auto* v = std::get_if<double>(&value);
                if (!v)
                    return key + ": type";
                if (!std::isfinite(*v))
                    return key + ": finite";
                if (*v < 0)
                    return key + ": minimum";
                if (*v > 1)
                    return key + ": maximum";
            } else if (key == "compositor.dim_inactive") {
                const auto* v = std::get_if<bool>(&value);
                if (!v)
                    return key + ": type";
            } else if (key == "compositor.dim_modal") {
                const auto* v = std::get_if<bool>(&value);
                if (!v)
                    return key + ": type";
            } else if (key == "compositor.dim_strength") {
                const auto* v = std::get_if<double>(&value);
                if (!v)
                    return key + ": type";
                if (!std::isfinite(*v))
                    return key + ": finite";
                if (*v < 0)
                    return key + ": minimum";
                if (*v > 1)
                    return key + ": maximum";
            } else if (key == "compositor.dim_around") {
                const auto* v = std::get_if<double>(&value);
                if (!v)
                    return key + ": type";
                if (!std::isfinite(*v))
                    return key + ": finite";
                if (*v < 0)
                    return key + ": minimum";
                if (*v > 1)
                    return key + ": maximum";
            } else if (key == "compositor.blur_popups") {
                const auto* v = std::get_if<bool>(&value);
                if (!v)
                    return key + ": type";
            } else if (key == "compositor.blur_input_methods") {
                const auto* v = std::get_if<bool>(&value);
                if (!v)
                    return key + ": type";
            } else if (key == "compositor.render_unfocused_fps") {
                const auto* v = std::get_if<int64_t>(&value);
                if (!v)
                    return key + ": type";
                if (*v < 1)
                    return key + ": minimum";
                if (*v > 120)
                    return key + ": maximum";
            } else if (key == "compositor.zoom_rigid") {
                const auto* v = std::get_if<bool>(&value);
                if (!v)
                    return key + ": type";
            } else if (key == "compositor.zoom_detached_camera") {
                const auto* v = std::get_if<bool>(&value);
                if (!v)
                    return key + ": type";
            } else if (key == "compositor.zoom_disable_aa") {
                const auto* v = std::get_if<bool>(&value);
                if (!v)
                    return key + ": type";
            } else if (key == "compositor.pointer_focus_output") {
                const auto* v = std::get_if<bool>(&value);
                if (!v)
                    return key + ": type";
            } else if (key == "compositor.fullscreen_focus_policy") {
                const auto* v = std::get_if<int64_t>(&value);
                if (!v)
                    return key + ": type";
                if (*v < 0)
                    return key + ": minimum";
                if (*v > 2)
                    return key + ": maximum";
            } else if (key == "compositor.fullscreen_after_close") {
                const auto* v = std::get_if<bool>(&value);
                if (!v)
                    return key + ": type";
            } else if (key == "compositor.xwayland_nearest_neighbor") {
                const auto* v = std::get_if<bool>(&value);
                if (!v)
                    return key + ": type";
            } else if (key == "compositor.allow_tearing") {
                const auto* v = std::get_if<bool>(&value);
                if (!v)
                    return key + ": type";
            } else if (key == "compositor.cursor_start_output") {
                const auto* v = std::get_if<std::string>(&value);
                if (!v)
                    return key + ": type";
                static const std::regex pattern("[^\\x00-\\x1f\\x7f]{0,256}");
                if (!std::regex_match(*v, pattern))
                    return key + ": format";
            } else if (key == "compositor.zoom_factor") {
                const auto* v = std::get_if<double>(&value);
                if (!v)
                    return key + ": type";
                if (!std::isfinite(*v))
                    return key + ": finite";
                if (*v < 1)
                    return key + ": minimum";
                if (*v > 10)
                    return key + ": maximum";
            } else if (key == "compositor.locale") {
                const auto* v = std::get_if<std::string>(&value);
                if (!v)
                    return key + ": type";
                static const std::regex pattern("[^\\x00-\\x1f\\x7f]{0,256}");
                if (!std::regex_match(*v, pattern))
                    return key + ": format";
            } else if (key == "compositor.font_family") {
                const auto* v = std::get_if<std::string>(&value);
                if (!v)
                    return key + ": type";
                static const std::regex pattern("[^\\x00-\\x1f\\x7f]{1,256}");
                if (!std::regex_match(*v, pattern))
                    return key + ": format";
            } else if (key == "compositor.wake_on_key") {
                const auto* v = std::get_if<bool>(&value);
                if (!v)
                    return key + ": type";
            } else if (key == "compositor.wake_on_pointer") {
                const auto* v = std::get_if<bool>(&value);
                if (!v)
                    return key + ": type";
            } else if (key == "compositor.display_idle_minutes") {
                const auto* v = std::get_if<int64_t>(&value);
                if (!v)
                    return key + ": type";
                if (*v < 0)
                    return key + ": minimum";
                if (*v > 1440)
                    return key + ": maximum";
            } else if (key == "compositor.primary_selection") {
                const auto* v = std::get_if<bool>(&value);
                if (!v)
                    return key + ": type";
            } else if (key == "compositor.auto_hdr") {
                const auto* v = std::get_if<int64_t>(&value);
                if (!v)
                    return key + ": type";
                if (*v < 0)
                    return key + ": minimum";
                if (*v > 2)
                    return key + ": maximum";
                if (*v != int64_t{0} && *v != int64_t{1} && *v != int64_t{2})
                    return key + ": choice";
            } else if (key == "compositor.sdr_transfer") {
                const auto* v = std::get_if<std::string>(&value);
                if (!v)
                    return key + ": type";
                if (*v != std::string{"default"} && *v != std::string{"auto"} && *v != std::string{"srgb"} && *v != std::string{"gamma22"} && *v != std::string{"gamma22force"})
                    return key + ": choice";
            } else if (key == "compositor.icc_vcgt") {
                const auto* v = std::get_if<bool>(&value);
                if (!v)
                    return key + ": type";
            } else if (key == "compositor.xwayland_native_pixels") {
                const auto* v = std::get_if<bool>(&value);
                if (!v)
                    return key + ": type";
            } else if (key == "compositor.background_color") {
                const auto* v = std::get_if<std::string>(&value);
                if (!v)
                    return key + ": type";
                static const std::regex pattern("[0-9a-f]{8}");
                if (!std::regex_match(*v, pattern))
                    return key + ": format";
            } else if (key == "compositor.shadow_enabled") {
                const auto* v = std::get_if<bool>(&value);
                if (!v)
                    return key + ": type";
            } else if (key == "compositor.shadow_range") {
                const auto* v = std::get_if<int64_t>(&value);
                if (!v)
                    return key + ": type";
                if (*v < 0)
                    return key + ": minimum";
                if (*v > 100)
                    return key + ": maximum";
            } else if (key == "compositor.shadow_power") {
                const auto* v = std::get_if<int64_t>(&value);
                if (!v)
                    return key + ": type";
                if (*v < 1)
                    return key + ": minimum";
                if (*v > 4)
                    return key + ": maximum";
            } else if (key == "compositor.shadow_sharp") {
                const auto* v = std::get_if<bool>(&value);
                if (!v)
                    return key + ": type";
            } else if (key == "compositor.shadow_color") {
                const auto* v = std::get_if<std::string>(&value);
                if (!v)
                    return key + ": type";
                static const std::regex pattern("[0-9a-f]{8}( [0-9a-f]{8}){0,9} ([0-9]|[1-9][0-9]|[12][0-9]{2}|3[0-5][0-9])deg");
                if (!std::regex_match(*v, pattern))
                    return key + ": format";
            } else if (key == "compositor.shadow_inactive_color") {
                const auto* v = std::get_if<std::string>(&value);
                if (!v)
                    return key + ": type";
                static const std::regex pattern("inherit|[0-9a-f]{8}( [0-9a-f]{8}){0,9} ([0-9]|[1-9][0-9]|[12][0-9]{2}|3[0-5][0-9])deg");
                if (!std::regex_match(*v, pattern))
                    return key + ": format";
            } else if (key == "compositor.shadow_scale") {
                const auto* v = std::get_if<double>(&value);
                if (!v)
                    return key + ": type";
                if (!std::isfinite(*v))
                    return key + ": finite";
                if (*v < 0)
                    return key + ": minimum";
                if (*v > 1)
                    return key + ": maximum";
            } else if (key == "compositor.shadow_offset_x") {
                const auto* v = std::get_if<double>(&value);
                if (!v)
                    return key + ": type";
                if (!std::isfinite(*v))
                    return key + ": finite";
                if (*v < -250)
                    return key + ": minimum";
                if (*v > 250)
                    return key + ": maximum";
            } else if (key == "compositor.shadow_offset_y") {
                const auto* v = std::get_if<double>(&value);
                if (!v)
                    return key + ": type";
                if (!std::isfinite(*v))
                    return key + ": finite";
                if (*v < -250)
                    return key + ": minimum";
                if (*v > 250)
                    return key + ": maximum";
            } else if (key == "compositor.float_gap_top") {
                const auto* v = std::get_if<int64_t>(&value);
                if (!v)
                    return key + ": type";
                if (*v < 0)
                    return key + ": minimum";
                if (*v > 100)
                    return key + ": maximum";
            } else if (key == "compositor.float_gap_right") {
                const auto* v = std::get_if<int64_t>(&value);
                if (!v)
                    return key + ": type";
                if (*v < 0)
                    return key + ": minimum";
                if (*v > 100)
                    return key + ": maximum";
            } else if (key == "compositor.float_gap_bottom") {
                const auto* v = std::get_if<int64_t>(&value);
                if (!v)
                    return key + ": type";
                if (*v < 0)
                    return key + ": minimum";
                if (*v > 100)
                    return key + ": maximum";
            } else if (key == "compositor.float_gap_left") {
                const auto* v = std::get_if<int64_t>(&value);
                if (!v)
                    return key + ": type";
                if (*v < 0)
                    return key + ": minimum";
                if (*v > 100)
                    return key + ": maximum";
            } else if (key == "compositor.color_management") {
                const auto* v = std::get_if<bool>(&value);
                if (!v)
                    return key + ": type";
            } else if (key == "compositor.lock_background") {
                const auto* v = std::get_if<bool>(&value);
                if (!v)
                    return key + ": type";
            } else if (key == "compositor.lock_blur") {
                const auto* v = std::get_if<bool>(&value);
                if (!v)
                    return key + ": type";
            } else if (key == "compositor.swallow_enabled") {
                const auto* v = std::get_if<bool>(&value);
                if (!v)
                    return key + ": type";
            } else if (key == "compositor.swallow_regex") {
                const auto* v = std::get_if<std::string>(&value);
                if (!v)
                    return key + ": type";
            } else if (key == "compositor.swallow_exception_regex") {
                const auto* v = std::get_if<std::string>(&value);
                if (!v)
                    return key + ": type";
            } else if (key == "compositor.screen_shader") {
                const auto* v = std::get_if<std::string>(&value);
                if (!v)
                    return key + ": type";
            } else if (key == "compositor.motion_blur_enabled") {
                const auto* v = std::get_if<bool>(&value);
                if (!v)
                    return key + ": type";
            } else if (key == "compositor.motion_blur_samples") {
                const auto* v = std::get_if<int64_t>(&value);
                if (!v)
                    return key + ": type";
                if (*v < 1)
                    return key + ": minimum";
                if (*v > 64)
                    return key + ": maximum";
            } else if (key == "compositor.snap_enabled") {
                const auto* v = std::get_if<bool>(&value);
                if (!v)
                    return key + ": type";
            } else if (key == "compositor.snap_window_gap") {
                const auto* v = std::get_if<int64_t>(&value);
                if (!v)
                    return key + ": type";
                if (*v < 0)
                    return key + ": minimum";
                if (*v > 100)
                    return key + ": maximum";
            } else if (key == "compositor.snap_monitor_gap") {
                const auto* v = std::get_if<int64_t>(&value);
                if (!v)
                    return key + ": type";
                if (*v < 0)
                    return key + ": minimum";
                if (*v > 100)
                    return key + ": maximum";
            } else if (key == "compositor.snap_border_overlap") {
                const auto* v = std::get_if<bool>(&value);
                if (!v)
                    return key + ": type";
            } else if (key == "compositor.snap_respect_gaps") {
                const auto* v = std::get_if<bool>(&value);
                if (!v)
                    return key + ": type";
            } else
                return key + ": unknown";
        }
        auto resolved = defaults();
        for (const auto& [key, value] : values)
            resolved[key] = value;
        if (std::get<double>(resolved.at("compositor.inactive_opacity")) > std::get<double>(resolved.at("compositor.active_opacity")))
            return "compositor.inactive_opacity: ordering";
        if (std::get<std::string>(resolved.at("motion.preset")) == std::string{"custom"} && !std::get<bool>(resolved.at("motion.enabled")))
            return "motion.preset: requires";
        if (std::get<bool>(resolved.at("compositor.lock_blur")) == true && !std::get<bool>(resolved.at("compositor.lock_background")))
            return "compositor.lock_blur: requires";
        return {};
    }
}
