// Generated by config/schema/generate_settings.py; do not edit.
#pragma once
#include <cstdint>
#include <map>
#include <string>
#include <variant>

namespace Luminophore::Settings {
    using Value    = std::variant<int64_t, double, bool, std::string>;
    using Snapshot = std::map<std::string, Value>;
    Snapshot defaults();
    // Empty string means valid. Validation does not mutate the input.
    std::string validate(const Snapshot& values);
}
