#include "LuminophoreConfigManager.hpp"
#include "InputRuntime.hpp"
#include "GeneralSettings.hpp"
#include "SettingsGeneration.hpp"
#include "DesktopSettings.hpp"
#include "../shared/monitor/MonitorRuleManager.hpp"
#include "../values/ConfigValues.hpp"
#include "../../Compositor.hpp"
#include "../../event/EventBus.hpp"
#include "../../errorOverlay/Overlay.hpp"
#include <algorithm>
#include <fstream>
#include <map>
#include <stdexcept>

using namespace Luminophore::Settings;

static std::string canonical(std::string name) {
    std::ranges::replace(name, '.', ':');
    return name;
}

struct CLuminophoreConfigManager::SStorage {
    struct ICell {
        virtual ~ICell()                           = default;
        virtual Config::SConfigOptionReply reply() = 0;
    };
    template <typename T>
    struct SCell final : ICell {
        T     value;
        void* pointer = &value;
        explicit SCell(T initial) : value(std::move(initial)) {
            ;
        }
        Config::SConfigOptionReply reply() override {
            return {.dataptr = &pointer, .type = &typeid(T)};
        }
    };
    std::map<std::string, std::unique_ptr<ICell>> cells;
    template <typename T>
    void add(const std::string& name, T value) {
        if (!cells.emplace(canonical(name), std::make_unique<SCell<T>>(std::move(value))).second)
            throw std::runtime_error("duplicate native config value: " + name);
    }
    template <typename Declaration>
    bool addDefault(const SP<Config::Values::IValue>& declaration) {
        auto* typed = dynamic_cast<Declaration*>(declaration.get());
        if (!typed)
            return false;
        add(declaration->name(), typed->defaultVal());
        return true;
    }
    template <typename T>
    void set(const std::string& name, T value) {
        auto* cell = dynamic_cast<SCell<T>*>(cells.at(canonical(name)).get());
        if (!cell)
            throw std::runtime_error("native config type mismatch: " + name);
        cell->value = std::move(value);
    }
};

CLuminophoreConfigManager::CLuminophoreConfigManager() : m_storage(std::make_unique<SStorage>()) {
    using namespace Config::Values;
    // Shared declarations supply migration defaults, never mutable loader storage.
    for (const auto& declaration : CONFIG_VALUES) {
        const bool added = m_storage->addDefault<Bool>(declaration) || m_storage->addDefault<Color>(declaration) || m_storage->addDefault<CssGap>(declaration) ||
            m_storage->addDefault<Float>(declaration) || m_storage->addDefault<FontWeight>(declaration) || m_storage->addDefault<Gradient>(declaration) ||
            m_storage->addDefault<Int>(declaration) || m_storage->addDefault<String>(declaration) || m_storage->addDefault<Vec2>(declaration);
        if (!added)
            throw std::runtime_error(std::string("unsupported native declaration: ") + declaration->name());
    }
    m_storage->add("autogenerated", Config::INTEGER{0});
    const auto root = settingsFixtureRoot();
    const auto boot = CSettingsGenerations(root).bootstrap();
    m_storage->add("luminophore:next_session_cm_enabled", std::get<bool>(boot.values.at("compositor.color_management")));
    m_storage->set("render:cm_enabled", std::get<bool>(boot.values.at("compositor.color_management")));
    m_storage->set("misc:session_lock_xray", std::get<bool>(boot.values.at("compositor.lock_background")));
    m_storage->set("misc:session_lock_blur", std::get<bool>(boot.values.at("compositor.lock_blur")));
    m_storage->add("luminophore:shadow_inactive_inherit", std::get<std::string>(boot.values.at("compositor.shadow_inactive_color")) == "inherit");
    refreshPaths();
    m_storage->set("cursor:default_monitor",
                   (std::get<std::string>(boot.values.at("compositor.cursor_start_output")).empty() ? std::string{STRVAL_EMPTY} :
                                                                                                      std::get<std::string>(boot.values.at("compositor.cursor_start_output"))));
    m_storage->set("cursor:zoom_factor", static_cast<Config::FLOAT>(std::get<double>(boot.values.at("compositor.zoom_factor"))));
    m_storage->set("general:locale", std::get<std::string>(boot.values.at("compositor.locale")));
    m_storage->set("misc:font_family", std::get<std::string>(boot.values.at("compositor.font_family")));
    m_storage->set("misc:key_press_enables_dpms", std::get<bool>(boot.values.at("compositor.wake_on_key")));
    m_storage->set("misc:mouse_move_enables_dpms", std::get<bool>(boot.values.at("compositor.wake_on_pointer")));
    m_storage->set("misc:luminophore_monitor_idle_minutes", std::get<int64_t>(boot.values.at("compositor.display_idle_minutes")));
    m_storage->set("misc:middle_click_paste", std::get<bool>(boot.values.at("compositor.primary_selection")));
    m_storage->set("render:cm_auto_hdr", std::get<int64_t>(boot.values.at("compositor.auto_hdr")));
    m_storage->set("render:cm_sdr_eotf", std::get<std::string>(boot.values.at("compositor.sdr_transfer")));
    m_storage->set("render:icc_vcgt_enabled", std::get<bool>(boot.values.at("compositor.icc_vcgt")));
    m_storage->set("xwayland:force_zero_scaling", std::get<bool>(boot.values.at("compositor.xwayland_native_pixels")));
    m_storage->set("misc:background_color", parseGeneralColor(std::get<std::string>(boot.values.at("compositor.background_color"))));
    m_storage->set("decoration:shadow:enabled", std::get<bool>(boot.values.at("compositor.shadow_enabled")));
    m_storage->set("decoration:shadow:range", std::get<int64_t>(boot.values.at("compositor.shadow_range")));
    m_storage->set("decoration:shadow:render_power", std::get<int64_t>(boot.values.at("compositor.shadow_power")));
    m_storage->set("decoration:shadow:sharp", std::get<bool>(boot.values.at("compositor.shadow_sharp")));
    m_storage->set("decoration:shadow:color", parseShadowGradient(std::get<std::string>(boot.values.at("compositor.shadow_color"))));
    m_storage->set("decoration:shadow:color_inactive", parseShadowGradient(std::get<std::string>(boot.values.at("compositor.shadow_inactive_color"))));
    m_storage->set("decoration:shadow:scale", static_cast<Config::FLOAT>(std::get<double>(boot.values.at("compositor.shadow_scale"))));
    m_storage->set("decoration:shadow:offset",
                   Config::VEC2{std::get<double>(boot.values.at("compositor.shadow_offset_x")), std::get<double>(boot.values.at("compositor.shadow_offset_y"))});
    m_storage->set("general:float_gaps",
                   Config::CCssGapData{std::get<int64_t>(boot.values.at("compositor.float_gap_top")), std::get<int64_t>(boot.values.at("compositor.float_gap_right")),
                                       std::get<int64_t>(boot.values.at("compositor.float_gap_bottom")), std::get<int64_t>(boot.values.at("compositor.float_gap_left"))});
    m_storage->set("xwayland:use_nearest_neighbor", std::get<bool>(boot.values.at("compositor.xwayland_nearest_neighbor")));
    m_storage->set("general:allow_tearing", std::get<bool>(boot.values.at("compositor.allow_tearing")));
    m_storage->set("misc:mouse_move_focuses_monitor", std::get<bool>(boot.values.at("compositor.pointer_focus_output")));
    m_storage->set("misc:on_focus_under_fullscreen", std::get<int64_t>(boot.values.at("compositor.fullscreen_focus_policy")));
    m_storage->set("misc:exit_window_retains_fullscreen", std::get<bool>(boot.values.at("compositor.fullscreen_after_close")));
    m_storage->set("cursor:zoom_rigid", std::get<bool>(boot.values.at("compositor.zoom_rigid")));
    m_storage->set("cursor:zoom_detached_camera", std::get<bool>(boot.values.at("compositor.zoom_detached_camera")));
    m_storage->set("cursor:zoom_disable_aa", std::get<bool>(boot.values.at("compositor.zoom_disable_aa")));
    m_storage->set("decoration:fullscreen_opacity", static_cast<Config::FLOAT>(std::get<double>(boot.values.at("compositor.fullscreen_opacity"))));
    m_storage->set("decoration:dim_inactive", std::get<bool>(boot.values.at("compositor.dim_inactive")));
    m_storage->set("decoration:dim_modal", std::get<bool>(boot.values.at("compositor.dim_modal")));
    m_storage->set("decoration:dim_strength", static_cast<Config::FLOAT>(std::get<double>(boot.values.at("compositor.dim_strength"))));
    m_storage->set("decoration:dim_around", static_cast<Config::FLOAT>(std::get<double>(boot.values.at("compositor.dim_around"))));
    m_storage->set("decoration:blur:popups", std::get<bool>(boot.values.at("compositor.blur_popups")));
    m_storage->set("decoration:blur:input_methods", std::get<bool>(boot.values.at("compositor.blur_input_methods")));
    m_storage->set("misc:render_unfocused_fps", std::get<int64_t>(boot.values.at("compositor.render_unfocused_fps")));
    m_storage->set("binds:drag_threshold", std::get<int64_t>(boot.values.at("input.drag_threshold")));
    m_storage->set("binds:scroll_event_delay", std::get<int64_t>(boot.values.at("input.scroll_event_delay")));
    m_storage->set("cursor:inactive_timeout", static_cast<Config::FLOAT>(std::get<double>(boot.values.at("input.cursor_inactive_timeout"))));
    m_storage->set("cursor:no_warps", std::get<bool>(boot.values.at("input.cursor_no_warps")));
    m_storage->set("cursor:persistent_warps", std::get<bool>(boot.values.at("input.cursor_persistent_warps")));
    m_storage->set("cursor:hide_on_key_press", std::get<bool>(boot.values.at("input.cursor_hide_on_key_press")));
    m_storage->set("cursor:hide_on_touch", std::get<bool>(boot.values.at("input.cursor_hide_on_touch")));
    m_storage->set("cursor:hide_on_tablet", std::get<bool>(boot.values.at("input.cursor_hide_on_tablet")));
    m_storage->set("cursor:warp_back_after_non_mouse_input", std::get<bool>(boot.values.at("input.cursor_warp_back_after_non_mouse_input")));
    m_storage->set("general:resize_on_border", std::get<bool>(boot.values.at("input.resize_on_border")));
    m_storage->set("general:extend_border_grab_area", std::get<int64_t>(boot.values.at("input.extend_border_grab_area")));
    m_storage->set("general:resize_on_border_inner_area", std::get<int64_t>(boot.values.at("input.resize_on_border_inner_area")));
    m_storage->set("general:hover_icon_on_border", std::get<bool>(boot.values.at("input.hover_icon_on_border")));
    m_storage->set("general:resize_corner", std::get<int64_t>(boot.values.at("input.resize_corner")));
    m_storage->set("gestures:close_max_timeout", std::get<int64_t>(boot.values.at("input.close_gesture_timeout")));
    // Populate before layout/input constructors bind ConfigValue addresses.
    const std::pair<const char*, const char*> ints[] = {
        {"border_size", "general:border_size"},
        {"rounding", "decoration:rounding"},
        {"default_view_columns", "misc:luminophore_default_view_columns"},
        {"default_view_rows", "misc:luminophore_default_view_rows"},
        {"blur_size", "decoration:blur:size"},
        {"blur_passes", "decoration:blur:passes"},
        {"vrr", "misc:vrr"},
    };
    for (const auto& [key, destination] : ints)
        m_storage->set(destination, std::get<int64_t>(boot.values.at(std::string("compositor.") + key)));
    for (const auto* key : {"active_opacity", "inactive_opacity", "dim_special"})
        m_storage->set(std::string("decoration:") + key, static_cast<Config::FLOAT>(std::get<double>(boot.values.at(std::string("compositor.") + key))));
    m_storage->set("input:touchpad:disable_while_typing", std::get<bool>(boot.values.at("touchpad.disable_while_typing")));
    m_storage->set("input:touchpad:natural_scroll", std::get<bool>(boot.values.at("touchpad.natural_scroll")));
    m_storage->set("input:touchpad:scroll_factor", static_cast<Config::FLOAT>(std::get<double>(boot.values.at("touchpad.scroll_factor"))));
    m_storage->set("input:touchpad:middle_button_emulation", std::get<bool>(boot.values.at("touchpad.middle_button_emulation")));
    m_storage->set("input:touchpad:tap_button_map", std::get<std::string>(boot.values.at("touchpad.tap_button_map")));
    m_storage->set("input:touchpad:clickfinger_behavior", std::get<bool>(boot.values.at("touchpad.clickfinger_behavior")));
    m_storage->set("input:touchpad:tap-to-click", std::get<bool>(boot.values.at("touchpad.tap_to_click")));
    m_storage->set("input:touchpad:drag_lock", std::get<int64_t>(boot.values.at("touchpad.drag_lock")));
    m_storage->set("input:touchpad:tap-and-drag", std::get<bool>(boot.values.at("touchpad.tap_and_drag")));
    m_storage->set("input:touchpad:flip_x", std::get<bool>(boot.values.at("touchpad.flip_x")));
    m_storage->set("input:touchpad:flip_y", std::get<bool>(boot.values.at("touchpad.flip_y")));
    m_storage->set("input:touchpad:drag_3fg", std::get<int64_t>(boot.values.at("touchpad.drag_3fg")));
    m_storage->set("input:touchdevice:transform", std::get<int64_t>(boot.values.at("touchdevice.transform")));
    m_storage->set("input:touchdevice:output", std::get<std::string>(boot.values.at("touchdevice.output")));
    m_storage->set("input:touchdevice:enabled", std::get<bool>(boot.values.at("touchdevice.enabled")));
    m_storage->set("input:virtualkeyboard:share_states", std::get<int64_t>(boot.values.at("virtualkeyboard.share_states")));
    m_storage->set("input:virtualkeyboard:release_pressed_on_close", std::get<bool>(boot.values.at("virtualkeyboard.release_pressed_on_close")));
    m_storage->set("input:tablet:transform", std::get<int64_t>(boot.values.at("tablet.transform")));
    m_storage->set("input:tablet:output", std::get<std::string>(boot.values.at("tablet.output")));
    m_storage->set("input:tablet:absolute_region_position", std::get<bool>(boot.values.at("tablet.absolute_region_position")));
    m_storage->set("input:tablet:relative_input", std::get<bool>(boot.values.at("tablet.relative_input")));
    m_storage->set("input:tablet:left_handed", std::get<bool>(boot.values.at("tablet.left_handed")));
    m_storage->set("input:tablettool:eraser_button_mode", std::get<int64_t>(boot.values.at("tablettool.eraser_button_mode")));
    m_storage->set("input:tablettool:eraser_button_override", std::get<int64_t>(boot.values.at("tablettool.eraser_button_override")));
    m_storage->set("input:tablettool:pressure_range_min", static_cast<Config::FLOAT>(std::get<double>(boot.values.at("tablettool.pressure_range_min"))));
    m_storage->set("input:tablettool:pressure_range_max", static_cast<Config::FLOAT>(std::get<double>(boot.values.at("tablettool.pressure_range_max"))));
    m_storage->set("input:tablet:region_position",
                   Config::VEC2{std::get<double>(boot.values.at("tablet.region_position_x")), std::get<double>(boot.values.at("tablet.region_position_y"))});
    m_storage->set("input:tablet:region_size", Config::VEC2{std::get<double>(boot.values.at("tablet.region_size_x")), std::get<double>(boot.values.at("tablet.region_size_y"))});
    m_storage->set("input:tablet:active_area_size",
                   Config::VEC2{std::get<double>(boot.values.at("tablet.active_area_size_x")), std::get<double>(boot.values.at("tablet.active_area_size_y"))});
    m_storage->set("input:tablet:active_area_position",
                   Config::VEC2{std::get<double>(boot.values.at("tablet.active_area_position_x")), std::get<double>(boot.values.at("tablet.active_area_position_y"))});
    validateInputGeneration(boot);
    m_devices = boot.devices;
    for (const auto* key : {"kb_layout", "kb_model", "kb_variant", "kb_options", "kb_rules"})
        m_storage->set(std::string("input:") + key, std::get<std::string>(boot.values.at(std::string("input.") + key)));
    m_storage->set("input:scroll_method", std::get<std::string>(boot.values.at("input.scroll_method")));
    m_storage->set("input:scroll_button", std::get<int64_t>(boot.values.at("input.scroll_button")));
    m_storage->set("input:scroll_button_lock", std::get<bool>(boot.values.at("input.scroll_button_lock")));
    m_storage->set("input:rotation", std::get<int64_t>(boot.values.at("input.rotation")));
    m_storage->set("input:numlock_by_default", std::get<bool>(boot.values.at("input.numlock_by_default")));
    m_storage->set("input:resolve_binds_by_sym", std::get<bool>(boot.values.at("input.resolve_binds_by_sym")));
    m_storage->set("input:follow_mouse", std::get<int64_t>(boot.values.at("input.follow_mouse")));
    m_storage->set("input:follow_mouse_threshold", static_cast<Config::FLOAT>(std::get<double>(boot.values.at("input.follow_mouse_threshold"))));
    m_storage->set("input:mouse_refocus", std::get<bool>(boot.values.at("input.mouse_refocus")));
    m_storage->set("input:follow_mouse_shrink", std::get<int64_t>(boot.values.at("input.follow_mouse_shrink")));
    m_storage->set("input:off_window_axis_events", std::get<int64_t>(boot.values.at("input.off_window_axis_events")));
    m_storage->set("input:emulate_discrete_scroll", std::get<int64_t>(boot.values.at("input.emulate_discrete_scroll")));
    m_storage->set("input:focus_on_close", std::get<int64_t>(boot.values.at("input.focus_on_close")));
    m_storage->set("input:float_switch_override_focus", std::get<int64_t>(boot.values.at("input.float_switch_override_focus")));
    m_storage->set("input:accel_profile", std::get<std::string>(boot.values.at("input.accel_profile")));
    m_storage->set("input:scroll_points", std::get<std::string>(boot.values.at("input.scroll_points")));
    m_storage->set("input:kb_file", std::get<std::string>(boot.values.at("input.kb_file")));
    m_storage->set("input:kb_snapshot", std::get<std::string>(boot.values.at("input.kb_snapshot")));
    m_storage->set("input:repeat_rate", std::get<int64_t>(boot.values.at("input.repeat_rate")));
    m_storage->set("input:repeat_delay", std::get<int64_t>(boot.values.at("input.repeat_delay")));
    m_storage->set("input:sensitivity", static_cast<Config::FLOAT>(std::get<double>(boot.values.at("input.sensitivity"))));
    m_storage->set("input:scroll_factor", static_cast<Config::FLOAT>(std::get<double>(boot.values.at("input.scroll_factor"))));
    m_storage->set("input:natural_scroll", std::get<bool>(boot.values.at("input.natural_scroll")));
    m_storage->set("input:left_handed", std::get<bool>(boot.values.at("input.left_handed")));
    m_storage->set("input:force_no_accel", std::get<bool>(boot.values.at("input.force_no_accel")));
    m_storage->set("decoration:blur:enabled", std::get<bool>(boot.values.at("compositor.blur_enabled")));
    for (const auto* key : {"gaps_in", "gaps_out"})
        m_storage->set(std::string("general:") + key, Config::CCssGapData(std::get<int64_t>(boot.values.at(std::string("compositor.") + key))));
    for (const auto& [key, destination] : std::map<std::string, std::string>{{"swallow_enabled", "misc:enable_swallow"},
                                                                             {"motion_blur_enabled", "decoration:motion_blur:enabled"},
                                                                             {"snap_enabled", "general:snap:enabled"},
                                                                             {"snap_border_overlap", "general:snap:border_overlap"},
                                                                             {"snap_respect_gaps", "general:snap:respect_gaps"}})
        m_storage->set(destination, std::get<bool>(boot.values.at("compositor." + key)));
    for (const auto& [key, destination] : std::map<std::string, std::string>{
             {"motion_blur_samples", "decoration:motion_blur:samples"}, {"snap_window_gap", "general:snap:window_gap"}, {"snap_monitor_gap", "general:snap:monitor_gap"}})
        m_storage->set(destination, std::get<int64_t>(boot.values.at("compositor." + key)));
    for (const auto& [key, destination] : std::map<std::string, std::string>{
             {"swallow_regex", "misc:swallow_regex"}, {"swallow_exception_regex", "misc:swallow_exception_regex"}, {"screen_shader", "decoration:screen_shader"}}) {
        const auto& text = std::get<std::string>(boot.values.at("compositor." + key));
        m_storage->set(destination, text.empty() ? std::string{STRVAL_EMPTY} : text);
    }
    m_storage->set("misc:disable_hyprland_logo", true);
    m_storage->set("misc:disable_splash_rendering", true);
    m_storage->set("misc:force_default_wallpaper", Config::INTEGER{0});
    m_storage->set("decoration:blur:special", true);
}
CLuminophoreConfigManager::~CLuminophoreConfigManager() = default;
Config::eConfigManagerType CLuminophoreConfigManager::type() {
    return Config::CONFIG_LUMINOPHORE;
}
void CLuminophoreConfigManager::init() {
    const auto settings = CSettingsGenerations(settingsFixtureRoot()).completed();
    installDesktopSettings(decodeDesktopSettings(settings.documents), true);
    for (const auto& [name, value] : settings.monitors) {
        Config::CMonitorRule rule;
        rule.m_name        = name;
        rule.m_vrr         = value.vrr;
        rule.m_resolution  = {value.width, value.height};
        rule.m_refreshRate = value.refresh;
        rule.m_scale       = value.scale;
        rule.m_transform   = static_cast<wl_output_transform>(value.transform);
        rule.m_disabled    = value.disabled;
        if (value.position)
            rule.m_offset = {value.position->first, value.position->second};
        Config::monitorRuleMgr()->add(std::move(rule));
    }

    const auto value               = getConfigValue("xwayland:enabled");
    g_pCompositor->m_wantsXwayland = *static_cast<bool*>(*value.dataptr);
    Event::bus()->m_events.config.reloaded.emit();
    if (std::getenv("LUMINOPHORE_SETTINGS_RECOVERY")) {
        m_error = "Luminophore settings recovery: temporary safe settings. Original files are preserved; edits in this session are temporary.";
        ErrorOverlay::overlay()->queueError(m_error);
    }
}
void CLuminophoreConfigManager::reload() {
    // Do not bypass the joint transaction or overwrite a prepared generation.
    m_error = "Use the Luminophore settings transaction; direct reload is unsupported";
}
std::string CLuminophoreConfigManager::verify() {
    try {
        CSettingsGenerations(settingsFixtureRoot()).completed();
        return "";
    } catch (const std::exception& e) { return e.what(); }
}
Config::SConfigOptionReply CLuminophoreConfigManager::getConfigValue(const std::string& name) {
    const auto it    = m_storage->cells.find(canonical(name));
    auto       reply = it == m_storage->cells.end() ? Config::SConfigOptionReply{} : it->second->reply();
    if (canonical(name) == "decoration:shadow:color_inactive") {
        const auto inherited = m_storage->cells.find("luminophore:shadow_inactive_inherit");
        if (inherited != m_storage->cells.end())
            reply.setByUser = !*static_cast<bool*>(*inherited->second->reply().dataptr);
    }
    return reply;
}
int CLuminophoreConfigManager::getDeviceInt(const std::string& name, const std::string& field, const std::string& fallback) {
    if (const auto value = deviceValue(name, field))
        return std::holds_alternative<bool>(*value) ? std::get<bool>(*value) : std::get<int64_t>(*value);
    const auto value = getConfigValue(fallback);
    if (!value.dataptr)
        return 0;
    if (*value.type == typeid(bool))
        return *static_cast<bool*>(*value.dataptr);
    if (*value.type == typeid(Config::INTEGER))
        return *static_cast<Config::INTEGER*>(*value.dataptr);
    throw std::runtime_error("device integer fallback type mismatch");
}
float CLuminophoreConfigManager::getDeviceFloat(const std::string& name, const std::string& field, const std::string& fallback) {
    if (const auto value = deviceValue(name, field))
        return std::get<double>(*value);
    const auto value = getConfigValue(fallback);
    if (!value.dataptr)
        return 0.F;
    if (*value.type != typeid(Config::FLOAT))
        throw std::runtime_error("device float fallback type mismatch");
    return *static_cast<Config::FLOAT*>(*value.dataptr);
}
Vector2D CLuminophoreConfigManager::getDeviceVec(const std::string& name, const std::string& field, const std::string& fallback) {
    const auto value = getConfigValue(fallback);
    if (!value.dataptr)
        return {};
    if (*value.type != typeid(Config::VEC2))
        throw std::runtime_error("device vector fallback type mismatch");
    const auto v = *static_cast<Config::VEC2*>(*value.dataptr);
    const auto x = deviceValue(name, field + "_x"), y = deviceValue(name, field + "_y");
    return {x ? std::get<double>(*x) : v.x, y ? std::get<double>(*y) : v.y};
}
std::string CLuminophoreConfigManager::getDeviceString(const std::string& name, const std::string& field, const std::string& fallback) {
    if (const auto value = deviceValue(name, field))
        return std::get<std::string>(*value);
    const auto value = getConfigValue(fallback);
    if (!value.dataptr)
        return "";
    if (*value.type != typeid(std::string))
        throw std::runtime_error("device string fallback type mismatch");
    const auto& v = *static_cast<std::string*>(*value.dataptr);
    return v == "[[EMPTY]]" ? "" : v;
}
const Value* CLuminophoreConfigManager::deviceValue(const std::string& name, const std::string& field) const {
    const auto device = m_devices.find(name);
    if (device == m_devices.end())
        return nullptr;
    auto key = field;
    std::replace(key.begin(), key.end(), '-', '_');
    const auto value = device->second.find(key);
    return value == device->second.end() ? nullptr : &value->second;
}
void CLuminophoreConfigManager::setDevices(const DeviceSettings& devices) {
    m_devices = devices;
}
const DeviceSettings& CLuminophoreConfigManager::devices() const {
    return m_devices;
}
bool CLuminophoreConfigManager::deviceConfigExplicitlySet(const std::string& name, const std::string& field) {
    return deviceValue(name, field);
}
bool CLuminophoreConfigManager::deviceConfigExists(const std::string& name) {
    return m_devices.contains(name);
}
void CLuminophoreConfigManager::refreshPaths() {
    const auto               root       = settingsFixtureRoot();
    const auto               generation = CSettingsGenerations(root).completed();
    std::vector<std::string> paths;
    for (const auto* file : {"settings.toml", "monitors.toml", "bindings.toml", "placement.toml", "bundles.toml"})
        paths.push_back((root / "generations" / generation.id / file).string());
    m_paths = std::move(paths);
}
std::string CLuminophoreConfigManager::getMainConfigPath() {
    refreshPaths();
    return m_paths.front();
}
std::string CLuminophoreConfigManager::currentConfigPath() {
    return getMainConfigPath();
}
std::string CLuminophoreConfigManager::getConfigString() {
    std::ifstream input(getMainConfigPath());
    return {std::istreambuf_iterator<char>(input), std::istreambuf_iterator<char>()};
}
const std::vector<std::string>& CLuminophoreConfigManager::getConfigPaths() {
    refreshPaths();
    return m_paths;
}
bool CLuminophoreConfigManager::configVerifPassed() {
    return m_error.empty();
}
std::string CLuminophoreConfigManager::getErrors() {
    return m_error;
}
std::expected<void, std::string> CLuminophoreConfigManager::generateDefaultConfig(const std::filesystem::path&, bool) {
    return std::unexpected("Native defaults are initialized by the five-file generation store");
}
void CLuminophoreConfigManager::handlePluginLoads() {
    ;
}
std::expected<void, std::string> CLuminophoreConfigManager::registerPluginValue(void*, SP<Config::Values::IValue>) {
    return std::unexpected("Plugin settings require native schema registration; legacy plugin config registration is unsupported");
}
void CLuminophoreConfigManager::onPluginUnload(void*) {
    ;
}

void CLuminophoreConfigManager::setDeviceSettings(const DeviceSettings& devices) {
    setDevices(devices);
}
DeviceSettings CLuminophoreConfigManager::deviceSettings() const {
    return devices();
}
