from __future__ import annotations

import json
import hashlib
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from .binding_registry import BindingAction, BindingRegistry


BINDING_PAYLOAD_VERSION = 1


def _row(action: BindingAction) -> dict[str, Any]:
    return {
        "action_id": action.action_id,
        "chord": action.chord,
        "flags": {
            "locked": action.flags.locked,
            "non_consuming": action.flags.non_consuming,
            "release": action.flags.release,
            "repeating": action.flags.repeating,
        },
        "group_id": action.group_id,
        "recovery": action.recovery,
    }


def binding_generation_id(registry: BindingRegistry) -> str:
    rows = [_row(action) for action in registry.actions]
    canonical = json.dumps(rows, ensure_ascii=False, sort_keys=True, separators=(",", ":")).encode("utf-8")
    return hashlib.sha256(canonical).hexdigest()


def serialize_binding_data(registry: BindingRegistry) -> bytes:
    rows = [_row(action) for action in registry.actions]
    return json.dumps(
        {
            "bindings": rows,
            "generation_id": binding_generation_id(registry),
            "version": BINDING_PAYLOAD_VERSION,
        },
        ensure_ascii=False,
        sort_keys=True,
        separators=(",", ":"),
    ).encode("utf-8")


def _lua_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def _lua_bool(value: bool) -> str:
    return "true" if value else "false"


def serialize_binding_lua(registry: BindingRegistry) -> bytes:
    lines = [
        "-- Generated by Luminophore binding registry. Do not edit.",
        "return {",
        f"  version = {BINDING_PAYLOAD_VERSION},",
        f"  generation_id = {_lua_string(binding_generation_id(registry))},",
        "  bindings = {",
    ]
    for action in registry.actions:
        chord = "nil" if action.chord is None else _lua_string(action.chord)
        lines.extend((
            "    {",
            f"      action_id = {_lua_string(action.action_id)},",
            f"      chord = {chord},",
            f"      group_id = {_lua_string(action.group_id)},",
            f"      recovery = {_lua_bool(action.recovery)},",
            "      flags = {"
            f" locked = {_lua_bool(action.flags.locked)},"
            f" non_consuming = {_lua_bool(action.flags.non_consuming)},"
            f" release = {_lua_bool(action.flags.release)},"
            f" repeating = {_lua_bool(action.flags.repeating)} }},",
            "    },",
        ))
    lines.extend(("  },", "}", ""))
    return "\n".join(lines).encode("utf-8")


__all__ = [
    "BINDING_PAYLOAD_VERSION", "binding_generation_id",
    "serialize_binding_data", "serialize_binding_lua",
]
