[preferred]
default=gtk
org.freedesktop.impl.portal.ScreenCast=luminophore
org.freedesktop.impl.portal.Screenshot=luminophore
org.freedesktop.impl.portal.GlobalShortcuts=luminophore
org.freedesktop.impl.portal.InputCapture=luminophore
